<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6HGP4Q4" ignored="0" name="SingleDeviceLogin" tests="9" failures="3" timestamp="17 Mar 2020 15:42:31 GMT" time="4.786" errors="0">
  <testcase name="InvalidEmail" time="2.137" classname="services.SingleDeviceLogin"/>
  <testcase name="ValidFepUserLogin" time="0.318" classname="services.SingleDeviceLogin"/>
  <testcase name="emptyEmail" time="0.051" classname="services.SingleDeviceLogin"/>
  <testcase name="emptyEmailEmptyPassword" time="0.053" classname="services.SingleDeviceLogin"/>
  <testcase name="loginWithDeactivatedUser" time="0.049" classname="services.SingleDeviceLogin">
    <failure type="java.lang.AssertionError" message="expected [-4] but found [-24]">
      <![CDATA[java.lang.AssertionError: expected [-4] but found [-24]
at services.SingleDeviceLogin.loginBase(SingleDeviceLogin.java:69)
at services.SingleDeviceLogin.loginWithDeactivatedUser(SingleDeviceLogin.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginWithDeactivatedUser -->
  <testcase name="loginWithValidEmailPasswordWrongDeviceID" time="0.312" classname="services.SingleDeviceLogin">
    <failure type="java.lang.AssertionError" message="expected [-4] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-4] but found [0]
at services.SingleDeviceLogin.loginBase(SingleDeviceLogin.java:69)
at services.SingleDeviceLogin.loginWithValidEmailPasswordWrongDeviceID(SingleDeviceLogin.java:136)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginWithValidEmailPasswordWrongDeviceID -->
  <testcase name="loginWithValidemailPasswordEmptyDeviceID" time="0.723" classname="services.SingleDeviceLogin">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;500&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <500>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:483)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:655)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:123)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:131)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:119)
at services.SingleDeviceLogin.loginBase(SingleDeviceLogin.java:57)
at services.SingleDeviceLogin.loginWithValidemailPasswordEmptyDeviceID(SingleDeviceLogin.java:144)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginWithValidemailPasswordEmptyDeviceID -->
  <testcase name="validEmailEmptyPassword" time="0.055" classname="services.SingleDeviceLogin"/>
  <testcase name="validEmailInvalidPassword" time="0.305" classname="services.SingleDeviceLogin"/>
</testsuite> <!-- SingleDeviceLogin -->
